CREATE DATABASE TableRelations
GO

USE TableRelations

 CREATE TABLE Passports(
 PassportID INT PRIMARY KEY
,PassportNumber CHAR(8) NOT NULL
)

 CREATE TABLE Persons (
 PersonID INT PRIMARY KEY IDENTITY
,FirstName VARCHAR(15) NOT NULL
,Salary DECIMAL(9, 2) NOT NULL
,PassportID INT FOREIGN
 KEY REFERENCES Passports (PassportID)
UNIQUE NOT NULL 
)
GO


CREATE TABLE Manufacturers (
ManufacturerID INT PRIMARY KEY IDENTITY
,[Name] VARCHAR(15) NOT NULL
,EstablishedOn DATE NOT NULL
)

CREATE TABLE Models(
 ModelID INT PRIMARY KEY IDENTITY(101, 1)
,[Name] VARCHAR(30) NOT NULL
,ManufacturerID INT FOREIGN KEY
REFERENCES Manufacturers (ManufacturerID)
)

INSERT INTO Manufacturers ([Name], EstablishedOn)
VALUES 
 ('BMW', '07/03/1916')
,('Tesla', '01/01/2003')
,('Lada', '01/05/1966')

INSERT INTO Models ([Name], ManufacturerID)
VALUES 
('X1', 1)
,('i6', 1)
,('Model S', 2)
,('Model X', 2)
,('Model 3', 2)
,('Nova', 3)
GO



CREATE TABLE Students(
 StudentID INT PRIMARY KEY IDENTITY
,[Name] VARCHAR(30) NOT NULL
)

CREATE TABLE Exams(
 ExamID INT PRIMARY KEY IDENTITY(101, 1)
,[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE StudentsExams(
StudentID INT FOREIGN KEY REFERENCES Students (StudentID)
,ExamID INT FOREIGN KEY REFERENCES  Exams (ExamID)
PRIMARY KEY (StudentID, ExamID)
)

INSERT INTO Students ([Name])
VALUES
('Mila')
,('Toni')
,('Ron')

INSERT INTO Exams ([Name])
VALUES
('SpringMVC')
,('Neo4j')
,('Oracle 11g')


INSERT INTO StudentsExams
VALUES
(1, 101)
,(1, 102)
,(2, 101)
,(3, 103)
,(2, 102)
,(2, 103)

GO



CREATE TABLE Teachers(
TeacherID INT PRIMARY KEY IDENTITY(101, 1)
,[Name] VARCHAR(15) NOT NULL
,ManagerID INT FOREIGN KEY REFERENCES Teachers(TeacherID) 
)

INSERT INTO Teachers ([Name], ManagerID)
VALUES 
('John', NULL)
,('Maya', 106)
,('Silvia', 106)
,('Ted', 105)
,('Mark', 101)
,('Greta', 101)

GO


CREATE TABLE ItemTypes(
 ItemTypeID Int PRIMARY KEY IDENTITY
,[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Items(
ItemID INT PRIMARY KEY IDENTITY
,[Name] VARCHAR(50)
,ItemTypeID INT FOREIGN KEY REFERENCES ItemTypes (ItemTypeID)
)

CREATE TABLE Cities (
CityID INT PRIMARY KEY
,[Name] VARCHAR(50)
)

CREATE TABLE Customers (
CustomerId INT PRIMARY KEY IDENTITY
,[Name] VARCHAR(50)
,BirthDate DATE
,CityID INT FOREIGN KEY REFERENCES Cities(CityID)
)

CREATE TABLE Orders(
OrderID INT PRIMARY KEY IDENTITY
,CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerId)
)

CREATE TABLE OrderItems(
OrderID INT FOREIGN KEY REFERENCES Orders(OrderID)
,ItemID INT FOREIGN KEY REFERENCES Items(ItemID)
PRIMARY KEY (OrderID, ItemID)
)
GO


USE TableRelations

CREATE TABLE Subjects(
SubjectID INT PRIMARY KEY IDENTITY
,SubjectName VARCHAR(30) NOT NULL
)


CREATE TABLE Majors(
MajorID INT PRIMARY KEY IDENTITY
,[Name] VARCHAR(30) NOT NULL
)

CREATE TABLE Students(
StudentID INT PRIMARY KEY IDENTITY
,StudentNumber INT NOT NULL
,StudentName VARCHAR(30) NOT NULL
,MajorID INT NOT NULL FOREIGN KEY REFERENCES Majors(MajorID)
)

CREATE TABLE Agenda(
StudentID INT FOREIGN KEY REFERENCES Students(StudentID)
,SubjectID INT FOREIGN KEY REFERENCES Subjects(SubjectID)
PRIMARY KEY (StudentID, SubjectID)
)

CREATE TABLE Payments(
PaymentID INT PRIMARY KEY IDENTITY
,PaymentDate DATE NOT NULL
,PaymentAmount FLOAT NOT NULL
,StudentID INT NOT NULL FOREIGN KEY REFERENCES Students(StudentID)
)
GO

